backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from rest_framework import routers

from directory import views
from backend.views import *

# Auto Gens URLs
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'clients', ClientViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('directory/', views.index, name='index'),
    path('directory/add_client', views.add_client, name='add_client'),
    path('directory/view_clients', views.view_clients, name='view_clients'),

    # Adds URLS from router
    path('', include(router.urls)),

    # Generic endpoint? TBH IDK What it does
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from decouple import config

from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token

from directory import views
from backend.views import *

# Auto Gens API URLs
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'cats', CatViewSet)
router.register(r'files', DocumentViewSet, basename='files')
router.register(r'photos', PhotoViewSet, basename='photos')
router.register(r'events', EventViewSet, basename='events')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('cat/', views.cat_profile, name='Cat Profile'),
    path('edit_profile/', views.update_cat),
    path('update_cat/', views.update_cat),
    path('intake/', views.intake_form, name='Intake Form'),

    path('document_upload/', views.document_upload),
    path('delete_document/', views.delete_document),
    path('photo_upload/', views.photo_upload),
    path('delete_photo/', views.delete_photo),

    path('events/', views.events, name='Events'),
    path('event/', views.single_event, name='Event'),
    path('delete_event/', views.delete_event),
    path('help/', views.help, name='help'),

    path('accounts/', include('django.contrib.auth.urls')),

    path('api/', include(router.urls)),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
]

if not config('ISPROD', default=True, cast=bool):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

directory/models.py
from django.db import models
import os
from datetime import date, timedelta
from multiselectfield import MultiSelectField

# keep outside of Cat class for easy import
PERSONALITY = (
    (1, 'Indoors only'),
    (2, 'Indoors and outdoor'),
    (3, 'Lap cat'),
    (4, 'Mellow'),
    (5, 'Active'),
    (6, 'Independent'),
    (7, 'Shy'),
    (8, 'Playful'),
    (9, 'Friendly'),
    (10, 'Curious'),
    (11, 'Feisty'),
    (12, 'Affectionate'),
    (13, 'Loves attention'),
    (14, 'Aloof'),
    (15, 'Swats when over stimulated'),
    (16, 'Needs quiet home'),
    (17, 'Likes to be held/picked up'),
    (18, 'Doesn\'t like to be held/picked up'),
    (19, 'Comfortable with other cats'),
    (20, 'Not comfortable with other cats'),
    (21, 'Comfortable with dogs'),
    (22, 'Not comfortable with dogs'),
    (23, 'Good with younger kids'),
    (24, 'Good with older kids'),
    (25, 'Needs a home with adults only'),
    (26, 'Needs time to get to know and trust you')
)

class Cat(models.Model):
    name = models.CharField(max_length=50)

    GENDERS = [
        ('M', 'Male'),
        ('F', 'Female')
    ]
    gender = models.CharField(max_length=2, choices=GENDERS)
    birthday = models.DateField()
    description = models.CharField(max_length=60) # basic description (color)
    breed = models.CharField(max_length=35)

    ITYPES = [('DSH', 'DSH'), ('DMH', 'DMH'), ('DLH', 'DLH')]
    itype = models.CharField(max_length=4, choices = ITYPES)

    STATUSES = [
        ('adopt', 'For adoption'),
        ('temporary', 'Temporary'),
        ('permanent', 'Permanent'),
    ]
    status = models.CharField(max_length=10, choices=STATUSES)
    arrival_date = models.DateField(default=date.today)
    arrival_details = models.TextField()
    medical_history = models.TextField()
    vaccinations = models.TextField()
    is_microchipped = models.BooleanField()
    flea_control_date = models.DateField()
    deworming_date = models.DateField()
    fiv_felv_date = models.DateField()
    special_needs = models.TextField(null=True, blank=True)
    personality = MultiSelectField(choices=PERSONALITY, max_choices=25, max_length=25)
    more_personality = models.TextField(null=True, blank=True)
    comments = models.TextField(null=True, blank=True)
    personal_exp = models.TextField(null=True, blank=True)
    hidden = models.BooleanField(default=False)

    def age(self):
        return round((date.today() - self.birthday).days / 365, 2)

    def __str__(self):
        return self.name + " ({0}/{1}){2}".format(self.age(), self.gender, hidden_title(self.hidden))

    class Meta:
        ordering = ["id"]

def upload_path(instance, filename):
    return 'cat_{0}/docs/{1}'.format(instance.cat_id, filename)

class Document(models.Model):
    cat_id = models.IntegerField()  # foreign keys are too difficult with custom path names
    document = models.FileField(upload_to=upload_path)
    description = models.CharField(max_length=60, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    public = models.BooleanField(default=True)
    hidden = models.BooleanField(default=False)

    def filename(self):
        return os.path.basename(self.document.name)

    def __str__(self):
        return Cat.objects.get(id=self.cat_id).name + " - " + clean_file_name(self.document.name) + hidden_title(self.hidden)

    class Meta:
        ordering = ["uploaded_at"]

def photo_path(instance, filename):
    return 'cat_{0}/photos/{1}'.format(instance.cat_id, filename)

class Photo(models.Model):
    cat_id = models.IntegerField()
    photo = models.FileField(upload_to=photo_path)
    description = models.CharField(max_length=60, blank=True, null=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    hidden = models.BooleanField(default=False)

    def filename(self):
        return os.path.basename(self.photo.name)

    def __str__(self):
        return Cat.objects.get(id=self.cat_id).name + " - " + clean_file_name(self.photo.name) + hidden_title(self.hidden)

    class Meta:
        ordering = ["uploaded_at"]

EVENT_TYPES = [
    ('vet', 'Vet Appointment'),
    ('adoption', 'Adoption Appointment'),
    ('foster', 'Foster Appointment'),
    ('volunteer', 'Volunteer Training')
]

class Event(models.Model):
    cat_id = models.CharField(max_length=8)
    title = models.CharField(max_length=60)

    event_type = models.CharField(max_length=9, choices=EVENT_TYPES)
    date = models.DateField()
    time = models.TimeField()
    notes = models.TextField(null=True, blank=True)
    hidden = models.BooleanField(default=False)

    def __str__(self):
        cat = "Volunteers" if self.cat_id == '0' else Cat.objects.get(id=self.cat_id).name
        return cat + " - " + self.title + hidden_title(self.hidden)

    class Meta:
        ordering = ["date", "time"]

def clean_file_name(fname):
    fstart = fname.find('s/') # this is the end of the pre-built file name
    return fname[fstart+2:]

def hidden_title(hiddenField):
    return " [Hidden]" if (hiddenField) else ""

directory/forms.py
from django import forms
from directory.models import Cat
from directory.models import Document 
from directory.models import Photo
from directory.models import Event 

class IntakeForm(forms.ModelForm):
    class Meta:
        model = Cat
        fields = [
            'name', 'gender', 'birthday', 'description', 'breed', 'itype', 'status',
            'arrival_date', 'arrival_details', 'medical_history', 'vaccinations',
            'is_microchipped', 'flea_control_date', 'deworming_date', 'fiv_felv_date', 
            'special_needs', 'personality', 'more_personality', 'comments', 
            'personal_exp'
        ]

class EditForm(forms.ModelForm):
    class Meta:
        model = Cat
        fields = [
            'name', 'gender', 'birthday', 'description', 'breed', 'itype', 'status',
            'arrival_date', 'arrival_details', 'medical_history', 'vaccinations',
            'is_microchipped', 'flea_control_date', 'deworming_date', 'fiv_felv_date', 
            'special_needs', 'personality', 'more_personality', 'comments', 
            'personal_exp'
        ]


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ['document', 'description']

class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['photo', 'description']

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['cat_id', 'title', 'event_type', 'date', 'time', 'notes']

backend/directory/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect 

from .forms import ClientForm
from .models import Client

# Create your views here.
def index(request):
   return HttpResponse("Hello World!")

def add_client(request):
   if request.method == 'POST':
      form = ClientForm(request.POST)
      if form.is_valid():
         data = form.cleaned_data
         client = Client(first_name = data.get('first_name'),
                         last_name = data.get('last_name'),
                         birthday = data.get('birthday'),
                         location = data.get('location'))
         client.save()

         return HttpResponseRedirect('view_clients')
   else:
      form = ClientForm()

   return render(request, 'add_client.html', {'form': form})

def view_clients(request):
   clients = Client.objects.all()
   print(clients)
   return render(request, 'view_clients.html', {'clients': clients})

directory/templates/add_event.html
{% extends 'single_form.html' %}{% load static %}
{% block formContent %}

<h2>Add Event</h2>
<form action="/event/" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_title">Event Name</label>
        <input type="text" class="form-control" name="title" id="id_title" maxlength="60" required>
    </div>

    <div class="form-group">
        <label for="id_type">Event Type</label>
        <select class="form-control" name="event_type" id="id_type" required>
            <option value="" selected disabled hidden>Select Event Type</option>
            <option value="vet">Vet Appointment</option>
            <option value="adoption">Adoption Appointment</option>
            <option value="foster">Foster Appointment</option>
            <option value="volunteer">Volunteer Training</option>
        </select>
    </div>

    <div class="form-group">
        <label for="id_cat">Select Cat</label>
        <select class="form-control" name="cat_id" id="cat_id" required>
            <option value="" selected disabled hidden>Select Cat</option>
            <option value="0">Volunteers [only for training]</option>
            {% for cat in cats %}
            <option value="{{ cat.id }}">{{cat.name}}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label for="id_datetime">Appointment Date</label>
        <div class="d-flex">
            <input type="date" class="form-control mr-3" name="date" id="id_datetime" required>
            <input type="time" class="form-control ml-3" name="time" required>
        </div>
    </div>
    <div class="form-group">
        <label for="id_notes">Notes</label>
        <textarea class="form-control" id="id_notes" name="notes" rows="3"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Create Event</button>
</form>
{% endblock %}

directory/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% if htitle is not None %}
    <title>{{ htitle }} - CPCP Cat Directory</title>
    {% else %}
    <title>CPCP Cat Directory</title>
    {% endif %}
    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet">
    <link href="{% static "css/scrolling-nav.css" %}" rel="stylesheet">
    <link href="{% static "css/custom.css" %}" rel="stylesheet">

    <link href="{% static "imgs/favicon.ico" %}" type="image/png" rel="shortcut icon">
</head>
<body id="page-top">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="/">
          <img src="{% static "imgs/logo.png" %}" width="35" height="30" class="d-inline-block align-top" alt="">
          Cal Poly Cat Program
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a class="nav-link" href="/">Home</a></li>
                {% if user.is_active %}
                <li class="nav-item"><a class="nav-link" href="/events">Events</a></li>
                <li class="nav-item"><a class="nav-link" href="/intake">Intake</a></li>
                {% endif %}
                <li class="nav-item"><a class="nav-link" href="/help">Help</a></li>
                {% if user.is_superuser %}
                <li class="nav-item"><a class="nav-link" href="/admin">Admin</a></li>
                {% endif %}
                {% if not user.is_active %}
                <li class="nav-item"><a class="nav-link" href="/accounts/login">Login</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="/accounts/logout">Logout</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block pageContent %}{% endblock pageContent %}

<footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Made with &#9829; by 
        <a href="https://calpoly.hack4impact.org" target="_blank" class="text-white">Hack4Impact - Cal Poly</a>
      </p>
    </div>
</footer>
</body>

<script src="{% static "js/jquery.js" %}"></script>
<script src="{% static "js/popper.js" %}"></script>
<script src="{% static "js/bootstrap.js" %}"></script>
<script src="{% static "js/custom.js" %}"></script>
</html>

directory/templates/documents.html
{% load static %}

{% if documents|length > 0 %}
<h4 class="mt-4">Documents</h4>

<ul class="list-group list-group-flush">
    {% for doc in documents %}
    <li class="list-group-item d-flex justify-content-between text-decoration-none">
        <div>
            <a href="{{ doc.document.url }}" target="_blank">{{ doc.filename }}</a>
            <span class="ml-1 text-dark">{{ doc.description }}</span></div>
        <div>
            <div class="badge badge-secondary ">{{ doc.uploaded_at }}</div>
            {% if user.is_active %}
            <a href="/delete_document?id={{ doc.id }}"><img src="{% static "imgs/trash.svg" %}"></a>
            {% endif %}
        </div>
    </li>
    {% endfor %}
</ul>
{% endif %}

{% if user.is_active %}
<h4 class="mt-4">Upload Document</h4>
<form action="/document_upload/" method="post" enctype="multipart/form-data" onsubmit="return loadingIcon(this)">
    {% csrf_token %}
    <input type="hidden" name="cat" value="{{ cat.id }}">
    <div class="form-group">
        <label for="id_document">Document:</label>
        <input type="file" name="document" id="id_document" required>
    </div>

    <div class="form-check">
      <input type="checkbox" class="form-check-input" id="id_is_public" name="is_public" checked>
      <label class="form-check-label" for="id_is_public">Is public?</label>
    </div>

    <div class="form-group">
        <label for="id_description">Description</label>
        <input type="text" class="form-control" name="description" id="id_description" maxlength="60">
    </div>
    <button type="submit" class="btn btn-primary">Upload</button>
    <img src="{% static "imgs/loading.gif" %}" width="50px" height="50px" class="loading-icon" style="visibility: hidden">
</form>
{% endif %}

directory/templates/edit_event.html
{% extends 'single_form.html' %}{% load static %}
{% block formContent %}

<h2>Edit Event</h2>
<form action="/event/" method="post">
    {% csrf_token %}
    <input type="hidden" name="event_id" value="{{event.id}}">
    <div class="form-group">
        <label for="id_title">Event Name</label>
        <input type="text" class="form-control" name="title" id="id_title" maxlength="60" value="{{event.title}}" required>
    </div>

    <div class="form-group">
        <label for="id_type">Event Type</label>
        <select class="form-control" name="event_type" id="id_type" required>
        {% if event.event_type == "vet" %}
            <option value="vet" selected>Vet Appointment</option>
            <option value="adoption">Adoption Appointment</option>
            <option value="foster">Foster Appointment</option>
            <option value="volunteer">Volunteer Training</option>
        {% elif event.event_type == "adoption" %}
            <option value="vet">Vet Appointment</option>
            <option value="adoption" selected>Adoption Appointment</option>
            <option value="foster">Foster Appointment</option>
            <option value="volunteer">Volunteer Training</option>
        {% elif event.event_type == "foster" %}
            <option value="vet">Vet Appointment</option>
            <option value="adoption">Adoption Appointment</option>
            <option value="foster" selected>Foster Appointment</option>
            <option value="volunteer">Volunteer Training</option>
        {% elif event.event_type == "volunteer" %}
            <option value="vet">Vet Appointment</option>
            <option value="adoption">Adoption Appointment</option>
            <option value="foster">Foster Appointment</option>
            <option value="volunteer" selected>Volunteer Training</option>
        {% endif %}
        </select>
    </div>

    <div class="form-group">
        <label for="id_cat">Select Cat</label>
        <select class="form-control" name="cat_id" id="cat_id" required>
            {% if cat.id == 0 %}
            <option value="0" selected>Volunteers [only for training]</option>
            {% else %}
            <option value="0">Volunteers [only for training]</option>
            {% endif %}

            {% for c in cats %}
            {% if c.id == cat.id %}
            <option value="{{ c.id }}" selected>{{c.name}}</option>
            {% else %}
            <option value="{{ c.id }}">{{c.name}}</option>
            {% endif %}
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label for="id_datetime">Appointment Date</label>
        <div class="d-flex">
            <input type="date" class="form-control mr-3" name="date" id="id_datetime" required value="{{event.date|date:'Y-m-d'}}">
            <input type="time" class="form-control ml-3" name="time" required value="{{event.time|date:'H:i'}}">
        </div>
    </div>

    <div class="form-group">
        <label for="id_notes">Notes</label>
        <textarea class="form-control" id="id_notes" name="notes" rows="3">{{event.notes}}</textarea>
    </div>
    <button type="submit" class="btn btn-primary">Save Event</button>
</form>
{% endblock %}

directory/templates/event.html
{% extends 'base.html' %}{% load static %}
{% block pageContent %}

<section id="#event">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <h2>{{ cat.name }} | {{ event.title }}</h2>
                <h5>{{event.date|date:'M j'}} - {{event.time|date:'h:ia'}}</h5>
                {% if event.event_type == "vet" %}
                <p>Vet Appointment</p>
                {% elif event.event_type == "adopt" %}
                <p>Adoption Appointment</p>
                {% elif event.event_type == "foster" %}
                <p>Foster Appointment</p>
                {% endif %}
                <h3>Notes</h3>
                {{event.notes}}
                <div class="d-flex justify-content-end mt-2">
                    <a class="mr-3 mt-1" href="/delete_event?id={{ event.id }}"><img src="{% static "imgs/trash.svg" %}"></a>
                    <a class="btn btn-primary" href="/event/?id={{event.id}}&action=edit">Edit Event</a>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

directory/templates/intake.html
{% extends 'single_form.html' %}{% load static %}
{% block formContent %}

{% if save is not None %}
<h2>{{ save.title }}</h2>
<form action="/edit_profile/" method="post">
<input type="hidden" value="{{ cat.id }}" name="id" />
{% else %}
<h2>Intake Form</h2>
<form action="/intake/" method="post">
{% endif %}
    {% csrf_token %}
    <div class="form-group required">
        <label for="id_name">Pet's Name</label>
        <input type="text" value="{{ cat.name }}" class="form-control" name="name" id="id_name" maxlength="50" required>
    </div>
    <div class="form-group required">
        <label for="id_gender">Gender</label>
        <select class="form-control" name="gender" id="id_gender" required>
            <option value="" {% if not cat.gender %}selected{% endif %} disabled hidden>Select gender</option>
            <option value="M" {% if cat.gender == "M" %}selected{% endif %}>Male</option>
            <option value="F" {% if cat.gender == "F" %}selected{% endif %}>Female</option>
        </select>
    </div>
    <div class="form-group required">
        <label for="id_birthday">Birthday</label>
        <input type="date" value="{{ cat.birthday|date:'Y-m-d' }}" class="form-control" name="birthday" id="id_birthday" required>
    </div>
    <div class="form-group required">
        <label for="id_description">Description (color)</label>
        <input type="text" value="{{ cat.description }}" class="form-control" name="description" id="id_description" maxlength="60" required>
    </div>
    <div class="form-group required">
        <label for="id_breed">Breed</label>
        <input type="text" value="{{ cat.breed }}" class="form-control" name="breed" id="id_breed" maxlength="35" required>
    </div>
    <div class="form-group required">
        <label for="id_itype">Type</label>
        <select class="form-control" name="itype" id="id_itype" required>
            <option value="" {% if not cat.itype %}selected{% endif %} disabled hidden>Select type</option>
            <option value="DSH" {% if cat.itype == "DSH" %}selected{% endif %}>DSH</option>
            <option value="DMH" {% if cat.itype == "DMH" %}selected{% endif %}>DMH</option>
            <option value="DLH" {% if cat.itype == "DLH" %}selected{% endif %}>DLH</option>
        </select>
    </div>
    <div class="form-group required">
        <label for="id_status">Status</label>
        <select class="form-control" name="status" id="id_status" required>
            <option value="" {% if not cat.status %}selected{% endif %} disabled hidden>Select type</option>
            <option value="adopt" {% if cat.status == "adopt" %}selected{% endif %}>For Adoption</option>
            <option value="temporary" {% if cat.status == "temporary" %}selected{% endif %}>Temporary</option>
            <option value="permanent" {% if cat.status == "permanent" %}selected{% endif %}>Permanent</option>
        </select>
    </div>
    <div class="form-group required">
        <label for="id_arrival_date">Arrival Date</label>
        <input type="date" value="{{ cat.arrival_date|date:'Y-m-d' }}" class="form-control" name="arrival_date" id="id_arrival_date" required>
    </div>
    <div class="form-group required">
        <label for="id_arrival_details">Arrival Details (reason coming to shelter)</label>
        <textarea class="form-control" id="id_arrival_details" name="arrival_details" required rows="3">{{ cat.arrival_details }}</textarea>
    </div>
    <div class="form-group required">
        <label for="id_medical_history">Brief Medical History</label>
        <textarea class="form-control" id="id_medical_history" name="medical_history" required rows="3">{{ cat.medical_history }}</textarea>
    </div>
    <div class="form-group required">
        <label for="id_vaccinations">Vaccinations</label>
        <textarea class="form-control" id="id_vaccinations" name="vaccinations" required rows="3">{{ cat.vaccinations }}</textarea>
    </div>
    <div class="form-check">
        <input type="checkbox" class="form-check-input" id="id_is_microchipped" name="is_microchipped" {% if cat.is_microchipped %}checked{% endif %}>
        <label class="form-check-label" for="id_is_microchipped">Is microchipped?</label>
    </div>
    <div class="form-group required">
        <label for="id_flea_control_date">Flea control, date applied</label>
        <input type="date" value="{{ cat.flea_control_date|date:'Y-m-d' }}" class="form-control" name="flea_control_date" id="id_flea_control_date" required>
    </div>
    <div class="form-group required">
        <label for="id_deworming_date">Deworming done on</label>
        <input type="date" value="{{ cat.deworming_date|date:'Y-m-d' }}" class="form-control" name="deworming_date" id="id_deworming_date" required>
    </div>
    <div class="form-group required">
        <label for="id_fiv_felv_date">FIV-FELV, date tested</label>
        <input type="date" value="{{ cat.fiv_felv_date|date:'Y-m-d' }}" class="form-control" name="fiv_felv_date" id="id_fiv_felv_date" required>
    </div>
    <div class="form-group">
        <label for="id_special_needs">Special Needs (meds, diet, etc.)</label>
        <textarea class="form-control" id="id_special_needs" name="special_needs" rows="3">{{ cat.special_needs }}</textarea>
    </div>

    <label>Choose the characteristics that best describe the cat's personality and traits</label>
    <div class="row form-group">
        <div class="col">
            {% for val, text in form.personality.field.choices %}
            {% if forloop.counter == 14 %}
        </div>
        <div class="col">
            {% endif %}
            <div class="form-check">
                <input class="form-check-input" type="checkbox" name="{{ form.personality.name }}"
                  value="{{ val }}" id="id_personality_{{ forloop.counter }}" {% if val|stringformat:"i" in cat.personality %}checked{% endif %}>
                <label class="form-check-label" for="id_personality_{{ forloop.counter }}">{{ text }}</label>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="form-group">
        <label for="id_more_personality">Additional traits</label>
        <textarea class="form-control" id="id_more_personality" name="more_personality" rows="3">{{ cat.more_personality }}</textarea>
    </div>
    <div class="form-group">
        <label for="id_comments">Comments</label>
        <textarea class="form-control" id="id_comments" name="comments" rows="4">{{ cat.comments }}</textarea>
    </div>
    <div class="form-group">
        <label for="id_personal_exp">Personal experiences with the cat</label>
        <textarea class="form-control" id="id_personal_exp" name="personal_exp" rows="4">{{ cat.personal_exp }}</textarea>
    </div>
    {% if save is not None %}
    <button type="submit" class="btn btn-primary">Save</button>
    {% else %}
    <button type="submit" class="btn btn-primary">Submit</button>
    {% endif %}
</form>

{% if photos and photos|length != 0 %}
<div class="pt-4">
    <h3>Photos</h3>
    <ul class="list-group list-group-flush">
        {% for photo in photos %}
        <li class="list-group-item d-flex justify-content-between text-decoration-none">
             <div>
                  <a href="{{ photo.photo.url }}" target="_blank">{{ photo.filename }}</a>
                  <span class="ml-1 text-dark">{{ photo.description }}</span></div>
             <div>
                  <div class="badge badge-secondary ">{{ photo.uploaded_at }}</div>
                  {% if user.is_active %}
                  <a href="/delete_photo?id={{ photo.id }}"><img src="{% static "imgs/trash.svg" %}"></a>
                  {% endif %}
              </div>
         </li>
        {% endfor %}
    </ul>
</div>
{% endif %}

{% endblock formContent %}

directory/templates/photos.html
{% load static %}

{% if photos|length > 0 %}
<div id="catImageCarousel" class="carousel slide mt-4" data-ride="carousel">
    <div class="carousel-inner bg-light" style="height: 300px">
        {% for photo in photos %}
        <div class="carousel-item h-100 {% if forloop.counter0 == 0 %}active{% endif %}">
            <img class="h-100 d-block mx-auto" src="{{ photo.photo.url }}" alt="{{ photo.description}}">
        </div>
        {% endfor %}
    </div>
 
    {% if photos|length > 1 %}
    <a class="carousel-control-prev" href="#catImageCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next text-primary" href="#catImageCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon text-primary" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
    {% endif %}
</div>
{% endif %}

{% if user.is_active %}
<h4 class="mt-4">Upload Photo</h4>
<form class="d-flex-inline" action="/photo_upload/" method="post" enctype="multipart/form-data" onsubmit="return loadingIcon(this)">
    {% csrf_token %}
    <input type="hidden" name="cat_id" value="{{ cat.id }}">
    <div class="form-group">
        <label for="id_photo">Photo: </label>
        <input type="file" name="photo" id="id_photo" required>
    </div>
    <div class="form-group">
        <label for="id_description">Description</label>
        <input type="text" class="form-control" name="description" id="id_description" maxlength="60">
    </div>
    <button type="submit" class="btn btn-primary">Upload</button>
    <img src="{% static "imgs/loading.gif" %}" width="50px" height="50px" class="loading-icon" style="visibility: hidden">
</form>
{% endif %}

directory/templates/single_form.html
{% extends 'base.html' %}{% load static %}
{% block pageContent %}
<section id="#form_content">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto">
                {% block formContent %}{% endblock formContent %}
             </div>
        </div>
    </div>
</section>
{% endblock pageContent %}